degree_sampling: uniform
density: 1.0
field: GF7
gb_type: shape
max_degree_F: 5
max_degree_G: 5
max_num_terms_F: 10
max_num_terms_G: 10
max_size_F: 4
num_duplicants: 1
num_samples_test: 10000
num_samples_train: 30000 # 1000000
num_var: 2
term_sampling: uniform # 　　　　　　　　　　　注意！
